###################
#automations.yaml #
###################

  -  alias: "Auto Lamps"
     trigger:
       - platform: sun
         event: sunset
         offset: '-00:45:00'

     action:
       service: light.turn_on
       entity_id: group.lamps

  -  alias: "lights off"
     trigger:
        -  platform: time
           at: '23:15:00'
     action: 
       service: light.turn_off
       entity_id: group.lamps


# Automation. 
    
 # This automation script runs when a value is received via MQTT on retained topic: setTemperature
 # It sets the value slider on the GUI. This slides also had its own automation when the value is changed.

  - alias: Set temp slider
    trigger:
      platform: mqtt
      topic: "setTemperature"
   # entity_id: input_slider.target_temp
    action:
       service: input_slider.select_value
       data_template:
        entity_id: input_slider.target_temp
        value: '{{ trigger.payload}}'

 # This automation script runs when the target temperature slider is moved.
 # It publishes its value to the same MQTT topic it is also subscribed to.
  - alias: Temp slider moved
    trigger:
      platform: state
      entity_id: input_slider.target_temp
    action:
      service: mqtt.publish
      data_template:
        topic: "setTemperature"
        retain: true
        payload: '{{ states.input_slider.target_temp.state | int }}'
